language: node_js
# sudo: required
services:
  - docker
before_install:
  - docker build -t lafountain/docker-react -f client/Dockerfile.dev .

script:
  - docker run -e CI=true lafountain/docker-react npm run test
