sudo: required
services:
  - docker
language: node_js

before_install:
  - phpenv global 7.0
    - docker build -t lafountain/docker-react -f client/Dockerfile.dev .

script:
  - docker run -e CI=true lafountain/docker-react npm run test
